val a = mul(3, add(2, 1));(* pass *)
val b = if eq(3, add(2, 1)) then "OK" else "NG";(* pass *)
val c = (123, false);(* pass *)
val c2 = (123, true);(* pass *)
val d = if #2 c then mul(#1 c, 2) else div(#1 c, 2);(* pass *)
val d2 = if #2 c2 then mul(#1 c2, 2) else div(#1 c2, 2);(* pass *)
fun e x = if eq(x, 0) then "zero" else "nonzero";(* pass *)
val f = (e 0, e 123);(* pass *)
fun g h = fn x => add(h x, h 123);(* pass *)
val i = g (fn z => mul(z, 2)) 456;(* pass *)
fun j x = if eq(x, 0) then 1 else mul(j sub(x, 1), x);(*pass*)
val k = j 3;(* pass *)
fun l x = (x, x);(* pass *)
val m = (fn x => #2 x, 123);(* pass *)
val n = (#1 m (l 456), #1 m (l "abc"));(* pass *)
fun fib x = if eq(x,1 )then 1 else if eq(x,2)then 1 else add(fib sub(x,1),fib sub(x,2));(* pass *)
